---
name: test ubuntu env
on:
  workflow_dispatch:
    branches:
      - test_ubuntu

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Starting
        run: echo "Starting... Be patient. ğŸ¢"
      - name: Checkout code âœ…
        uses: actions/checkout@v4
      - name: Build image tags ğŸ·ï¸
        id: build-tags
        run: |
          whoami
